### ISSUE TITLE
Race Condition with Asyncio in Python?

### ISSUE THREAD

**Issue by farvour** [pulumi/pulumi-fastly#87] opened 2021-02-12 04:29 UTC
I am encountering what seems to be a very unique scenario with this provider in Pulumi that is not an issue with Terraform, at least with the Python dialect:

I'm unable to create ACL entries because I cannot obtain the acl_id from the `.acls` property of Servicev1.

I'm also unable to create the resource without this ID even after I have the service_id available:

```raise TypeError("Missing required property 'acl_id'")
    TypeError: Missing required property 'acl_id'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

```pulumi_fastly.ServiceACLEntriesv1(
    f"{service_id}_{computed_acl.name}",
    entries=computed_acl_entries,
    service_id=service_id,
)
```

So, I thought, great, I'll iterate over the `Servicev1` objects, and just see if the name matches, to produce a list with the generator.... unfortunately this logic probably works fine in Terraform, but in Python asyncio it's completely busted.

If you follow the "way" in the Terraform documentation and turn that into Python, it results in a nasty race condition where the `.acl` objects are futures of themselves and causes an infinite loop... thus making it impossible to obtain the real `acl_id` from the params passed into the `Servicev1Args` (which seems to be the only way to tell Fastly to actually manage/create this with this provider.

https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_acl_entries_v1#example-usage-terraform--0126

```
            # Do the thing with the thing...
            self.servicesv1[service_name] = self.create_fastly_servicev1(
                service_name,
                backends=computed_backends,
                domains=computed_domains,
                headers=computed_headers,
                request_settings=computed_request_settings,
                conditions=computed_conditions,
                response_objects=computed_synthetic_responses,
                gzips=computed_gzips,
                vcl_snippets=computed_vcl_snippets,
                acls=list(map(lambda o: o[0], computed_acl_and_entries_args)),
                import_id=import_id,
            )

            # Since we needed the service ID to set the entries on the ACLs
            # (if applicable), do that here.

            for service_acl in self.servicesv1[service_name].acls:
                # This code causes an infinite loop....
                print(f"My future for acl_id object: {service_acl.acl_id}")
                continue
```

All this does is result in the future value for acl_id to be infinitely attempted... ... which never seems to fulfill the promise.

```p update -t 'urn:pulumi:prod::fastly-py::fastly:index/servicev1:Servicev1::<REDACTED>'
Previewing update (<REDACTED>/prod)

View Live: https://app.pulumi.com/<REDACTED>/fastly-py/prod/previews/<REDACTED>
     Type                 Name            Plan     Info
     pulumi:pulumi:Stack  fastly-py-prod           My future for acl_id object: <pulumi.output.Output object at 0x158617710>```

**Comment by farvour** [comment] 2021-02-12 04:34
And Object ID just rapidly changes over and over and over...

**Comment by farvour** [comment] 2021-02-12 05:58
Wanted to follow up here... I was able to workaround my problem by spending A LOT of time experimenting with Futures.. and it turns out that `pulumi.Output.all()` wasn't working at all, I'm not really sure why, but I had the information I needed in the clojure scope. I think this should still be investigated, as Pulumi should never really be allowed to infinitely hang up. I even updated to 2.20.0 and it didn't seem to change that piece.

Anyways, for anyone else having issues, here's the piece that produces my ServiceV1Entries!

`            # Do the thing with the thing...
            servicev1_obj = self.create_fastly_servicev1(
                service_name,
                backends=computed_backends,
                domains=computed_domains,
                headers=computed_headers,
                request_settings=computed_request_settings,
                conditions=computed_conditions,
                response_objects=computed_synthetic_responses,
                gzips=computed_gzips,
                vcl_snippets=computed_vcl_snippets,
                acls=computed_acl_args,
                import_id=import_id,
            )
            self.servicesv1[service_name] = servicev1_obj

            # Because Pulumi seems to "hang" when trying to iterate over a future
            # that is an iterable, use a known fixed bound and grab the index of
            # each acl property and run an individual apply() against it to generate
            # the ServiceACLEntriesv1 object.

            service_id = servicev1_obj.id

            for i in range(len(computed_acl_args)):
                computed_acl_name = computed_acl_args[i].name
                computed_acl_entries = computed_acl_entries_args[i]

                def service_acl_cb(a0) -> pulumi.Output:
                    pulumi_fastly.ServiceACLEntriesv1(
                        f"{service_id}-{computed_acl_name}",
                        acl_id=a0.acl_id,
                        entries=computed_acl_entries,
                        service_id=service_id,
                    )

                servicev1_obj.acls[i].apply(lambda args: service_acl_cb(args))`

**Comment by pgavlin** [comment] 2021-02-16 18:37
> Wanted to follow up here... I was able to workaround my problem by spending A LOT of time experimenting with Futures.. and it turns out that pulumi.Output.all() wasn't working at all without doing a dummy/placeholder pulumi.export() of the output. I'm not really sure why, but I had the information I needed in the resulting closure scope shown below. It would be nice to use pulumi.Output.all() without having to do this for this one scenario, however, and I think this should still be investigated. Pulumi should never really be allowed to infinitely hang up. I even updated to 2.20.0 and it didn't seem to change that piece.

It sounds like you're hitting https://github.com/pulumi/pulumi/issues/3991, so I'm going to close this as a duplicate of that issue.

**Closed by pgavlin** 2021-02-16 18:37 UTC
